version: "3"
services:
  netease-cloud:
    restart: always
    image: binaryify/netease_cloud_music_api
  qq-music-api:
    restart: always
    image: ???
  migu-music-api:
    restart: always
    image: ???
  music:
    image: listen-music
    environment:
      - NETEASE_CLOUD_URI=http://netease-cloud:3000
      - QQ_MUSIC_URI=http://qq-music-api:3300
      - MIGU_MUSIC_URI=http://migu-music-api :3400
    restart: always
  music-web:
    image: listen-music-web
    restart: always
    ports:
      - 8080:80
