swagger:
  enabled: true
  base-package: com.dezhishen.music
  title: "listen-music"
  description: "listen-music"
  version: "v1"
spring:
  resources:
    static-locations: classpath:templates/
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  ehcache:
    config: classpath:ehcache.xml
  session:
    store-type: none
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${music.data.path:${MUSIC_DATA_PATH:/listen_music_data}}/listen-music-db.sqlite
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
music-server:
  services:
    NeteaseCloud:
      enabled: true
      label: 网易云
      base-uri: ${NETEASE_CLOUD_URI:http://localhost:3000}
      api:
        song:
          uri: "/song/detail?ids={id}"
          root: "$.songs[0]"
          id: "$.id"
          name: "$.name"
          cover: "$.al.picUrl"
          artists:
            root: "$.ar"
            id: "$.id"
            name: "$.name"
        song-lyric:
          uri: "/lyric?id={id}"
          root: "$.lrc"
          lyric: "$.lyric"
        song-url:
          uri: "/song/url?id={id}"
          root: "$.data[0]"
          url: "$.url"
        search-song:
          uri: "/search?keywords={q}&limit={limit}&offset={offset}"
          root: "$.result"
          total: "$.songCount"
          list:
            root: "$.songs"
            id: "$.id"
            name: "$.name"
            artists:
              root: "$.artists"
              id: "$.id"
              name: "$.name"
        play-list:
          uri: "/playlist/detail?id={playListId}"
          root: "$.playlist"
          name: "$.name"
          id: "$.id"
          songs:
            root: "$.tracks"
            name: "$.name"
            id: "$.id"
          songIds: "$.trackIds[*].id"
    QQMusicApi:
      enabled: true
      label: QQ音乐
      base-uri: ${QQ_MUSIC_URI:http://localhost:3300}
      api:
        song-lyric:
          uri: "/lyric?songmid={id}"
          root: "$.data"
          lyric: "$.lyric"
        song:
          uri: "/song?songmid={id}"
          root: "$.data.track_info"
          id: "$.mid"
          name: "$.name"
          artists:
            root: "$.singer"
            id: "$.mid"
            name: "$.name"
        song-url:
          uri: "/song/urls?id={id}"
          root: "$.data.*"
          url: "$[0]"
        search-song:
          uri: "/search?key={q}&pageNo={pageNum}&pageSize={pageSize}"
          root: "$.data"
          total: "$.total"
          list:
            root: "$.list"
            id: "$.songmid"
            name: "$.songname"
            artists:
              root: "$.singer"
              id: "$.mid"
              name: "$.name"
    MiguMusicApi:
      enabled: true
      label: 咪咕音乐
      base-uri: ${MIGU_MUSIC_URI:http://localhost:3400}
      api:
        song-lyric:
          uri: "/lyric?cid={cid}"
          root: "$"
          lyric: "$.data"
          use-properties: true
        song:
          uri: "/song?id={id}"
          root: "$.data"
          id: "$.id"
          name: "$.name"
          cover: "$.album.picUrl"
          artists:
            root: "$.artists"
            id: "$.id"
            name: "$.name"
          process-properties: true
          properties-alias:
            cid: "$.cid"
        song-url:
          uri: "/song/url?id={id}"
          root: "$"
          url: "$.data"
        search-song:
          uri: "/search?keyword={q}&pageNo={pageNum}&pageSize={pageSize}"
          root: "$.data"
          total: "$.total"
          list:
            root: "$.list"
            id: "$.id"
            name: "$.name"
            artists:
              root: "$.artists"
              id: "$.id"
              name: "$.name"
auth:
  enabled: true
  ignore:
    - /system/account/register
    - /system/account/login
    - /
    - /index/**
    - /static/**