spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  session:
    store-type: redis
    redis.namespace: session
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:rootroot}
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  servlet:
    context-path: /api
music-server:
  sources:
    NeteaseCloud:
      label: 网易云
      enabled: true
      uri: ${NETEASE_CLOUD_URI:http://localhost:3000}
    MiguMusic:
      label: 咪咕
      enabled: true
      uri: ${MIGU_MUSIC_URI:http://localhost:3400}
    QqMusic:
      label: QQ音乐
      enabled: true
      uri: ${QQ_MUSIC_URI:http://localhost:3300}
biscuit-filter:
  ignore:
    - /biscuit/save