spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
music-server:
  sources:
    NeteaseCloud:
      uri: ${NETEASE_CLOUD_URI:http://localhost:3000}
    MiguMusic:
      uri: ${MIGU_MUSIC_URI:http://localhost:3400}
    QqMusic:
      uri: ${QQ_MUSIC_URI:http://localhost:3300}
