spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  session:
    store-type: redis
    redis.namespace: session
server:
  servlet:
    context-path: /api
music-server:
  sources:
    NeteaseCloud:
      label: 网易云
      enabled: true
      uri: ${NETEASE_CLOUD_URI:http://localhost:3000}
    MiguMusic:
      label: 咪咕
      enabled: true
      uri: ${MIGU_MUSIC_URI:http://localhost:3400}
    QqMusic:
      label: QQ音乐
      enabled: false
      uri: ${QQ_MUSIC_URI:http://localhost:3300}
biscuit-filter:
  ignore:
    - /biscuit/save